### ISSUE TITLE
No syntax highlighting on ReadTheDocs

### ISSUE THREAD

**Issue by rlafuente** [shoebot/sphinxcontrib-shoebot#1]
It works on a local version, but not when it's uploaded to ReadTheDocs.

I really don't know much about the internals to be able to deal with this, but would make things look prettier for sure.

**Comment by rlafuente** [comment]
This doesn't look like it's a Shoebot-only issue: on [this page](http://shoebot.readthedocs.io/en/latest/libraries.html#video-lib) there's simple Python snippets that aren't highlighted either. (it's still a problem that our docs aren't showing properly.)

**Comment by stuaxo** [comment]
If you find a RTD bug about this, might be worth linking here... last time I had a RTD bug it took a few years, but we may as well track it.

**Comment by stuaxo** [comment]
So I guess we need Shoebot work work something like
```.. code-block:: python.```

Sphinx is a bit of a black art to me.

**Comment by stuaxo** [comment]
Our Shoebot Directive should probably extend the code directive

https://github.com/sphinx-doc/sphinx/blob/master/sphinx/directives/code.py

I don't think I'm going to be able to look at this issue any time soon

**Comment by rlafuente** [comment]
not using rtd anymore, closing
